### ISSUE TITLE
Oceancraft Bug

### ISSUE THREAD

**Issue by meytro** [minecraftnero/minecraftnero#27]
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.Oceancraft.common.BlockCoral.func_149674_a(BlockCoral.java:45)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:569)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:288)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by meytro** [comment]
Oceancraft Weltgenerierung wurde deaktiviert um die Ursache einzuschränken.

**Comment by meytro** [comment]
Fixed by  removing Oceancraft https://github.com/minecraftnero/minecraftnero/commit/b81b884339daff91e16cba037e1e50d329793008
